---
- name: Ensure user has cluster admin access
  shell: oc policy can-i create clusterroles
  register: is_admin
  failed_when: is_admin.stdout == "no"
- name: Create cluster wide roles used by enmasse-admin service account
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/resources/cluster-roles/address-space-controller.yaml
- name: Grant address space controller cluster role privileges to service account
  shell: oc adm policy add-cluster-role-to-user enmasse.io:address-space-controller -n {{ namespace }} system:serviceaccount:{{ namespace }}:enmasse-admin
- name: Grant view policy to default SA
  shell: oc policy add-role-to-user view system:serviceaccount:{{ namespace }}:default -n {{ namespace }}
- name: Grant admin policy to enmasse-admin
  shell: oc policy add-role-to-user admin system:serviceaccount:{{ namespace }}:enmasse-admin -n {{ namespace }}
